### ISSUE TITLE
Not Work in Funko page

### ISSUE THREAD

**Issue by reinanegra** [Rilshrink/WebGLRipper#18]
They have updated the page and now the extension does not work

https://funko.com/build-your-custom-pop

**Comment by Rilshrink** [comment]
Should be fixed now, tell me how it goes

**Comment by reinanegra** [comment]
It still doesn't work for me and now it appears that there is an error in the minimun clears function

![image](https://github.com/Rilshrink/WebGLRipper/assets/164623138/fd559ae7-106d-4c44-b753-d59595be41f0)
![image](https://github.com/Rilshrink/WebGLRipper/assets/164623138/ffa46995-d872-4db2-bab0-93229ac27655)

**Comment by Rilshrink** [comment]
Seems like you edited the code?
```js
let minimumClears = document.getElementById('ripper_minimumClears').value;
```
Should be
```js
let minimumClears = document.getElementById('ripper_minimumclears').value;
```

And there isn't any need to edit the files as if you right click the extension in the bar on chrome you can open the options menu.
![chrome_extension_options_2](https://github.com/Rilshrink/WebGLRipper/assets/75235658/1d819de3-b20b-4c5d-8b61-8bb2296a1f76)
and you can then use the slider to set it to 4
![chrome_extension_options_look](https://github.com/Rilshrink/WebGLRipper/assets/75235658/a07ce84e-a0f2-4715-85ff-9e670f97e8ca)

**Comment by reinanegra** [comment]
Yes, I edited it, but the error appeared from the beginning.

Now it works, thank you very much <3

**Comment by Rilshrink** [comment]
No problem :)
